// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnoxmoyrzzakrmpbdrrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRub3htb3lyenpha3JtcGJkcnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MjY4MDgsImV4cCI6MjA3NTAwMjgwOH0.PgKRODR3mIhGALPmyJrSHd1kNUG6i5FSql4pUvqgMZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});